### ISSUE TITLE
mlflow : Web UI Doesn't open

### ISSUE THREAD

**Issue by vatsaldhar25** [community-charts/helm-charts#109]
Post doing installation, the mlflow UI isn't opening via the configured domain address, though working via mlflow port forwarding on localhost:5000
The load balancer targets are also healthy and receiving traffic at port HTTP: 5000 

when I open https://mlflow-dev.MYDOMAIN.com on my web-browser
through the inspect element I can see on network tab

> You need to enable JavaScript to run this app.

also If I do a curl on localhost:5000 or the domain name, I get the same response. 

App and Chart version are latest.

Below is the values.yaml

```
replicaCount: 2

extraEnvVars:
  AWS_DEFAULT_REGION: ap-south-1

image:
  repository: burakince/mlflow
  pullPolicy: IfNotPresent
  tag: "2.22.0"

serviceAccount:
  name: mlflow-sa
  create: true

backendStore:
  postgres:
    enabled: true
    host: MY_DATABASE_URL
    port: 5432
    database: mlflow
    driver: psycopg2
  existingDatabaseSecret:
    name: "mlflow-postgres-secret"
    usernameKey: postgres-username
    passwordKey: postgres-password

artifactRoot:
  defaultArtifactRoot: "s3://MY_S3_BUCKET/mlruns"
  defaultArtifactsDestination: "s3://MY_S3_BUCKET/mlartifacts"
  s3:
    enabled: true
    bucket: quince-mlflow-artifact-store

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
  hosts:
    - host: mlflow-dev.MYDOMAIN.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
```
