### ISSUE TITLE
mlflow freezes in webui

### ISSUE THREAD

**Issue by FerMiguelao** [community-charts/helm-charts#110]
After installation via helm chart, tried either creating a new prompt or deleting and existing model but webui freezes completely after clicking on the button. There's also no logs for error or even warning on the pods.
I also tried both using the ingress or port-forwarding, both had the same problem, so I think it should not be network related 

Here are the values im currently using for mlflow, with anonymized data for postgresql. I already applied the migration so I removed the option from the values file
```
mlflow:
  replicaCount: 2
  backendStore:
    postgres:
      enabled: true
      host: mlflow
      port: 5432
      database: mlflow
      user: mlflow
      password: mlflow
```
I'm new to using mlflow, so sorry in advance. Any help would be greatly appreciated
