### ISSUE TITLE
MLflow S3 Artifact Upload Requires AWS Login

### ISSUE THREAD

**Issue by skhan1229** [community-charts/helm-charts#111]
When I try to upload an artifact to mlflow, I get the error `NoCredentialsError: Unable to locate credentials`. The error goes away if I log in using the aws cli.

I noticed that there is a separate option for enabling proxy access (`proxiedArtifactStorage: true`). I have now enabled it in my deployment, but the issue still persists. This is my `values.yaml` file:

```yaml
artifactRoot:
  proxiedArtifactStorage: true
  s3:
    bucket: my-mlflow-artifact-store
    enabled: true
autoscaling:
  enabled: true
  maxReplicas: 3
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
backendStore:
  existingDatabaseSecret:
    name: mlflow-postgres-secret
    passwordKey: postgres-password
    usernameKey: postgres-username
  postgres:
    database: mlflow
    driver: psycopg2
    enabled: true
    host: example-db.region.rds.amazonaws.com
    port: 5432
extraEnvVars:
  AWS_DEFAULT_REGION: region-1
image:
  pullPolicy: IfNotPresent
  repository: burakince/mlflow
  tag: 2.22.0
ingress:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:region-1:123456789012:certificate/abcdef12-3456-7890-abcd-ef1234567890
    alb.ingress.kubernetes.io/group.name: ml-alb-pvt-ingress
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8000}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=Infrastructure
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  className: alb
  enabled: true
  hosts:
  - host: mlflow.example.com
    paths:
    - path: /
      pathType: Prefix
replicaCount: 2
resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/mlflow-eks-role
  create: true
  name: mlflow-sa
```
