### ISSUE TITLE
[n8n] Suspicious requests when running in isolated mode

### ISSUE THREAD

**Issue by orihomie** [community-charts/helm-charts#125]
Hi! I'm running my n8n installation in isolated mode, here's my override values file:

```
image:
  repository: my-proxy-registry/n8nio/n8n
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: "n8n"
fullnameOverride: "n8n"

podAnnotations: {}
podLabels: {}

db:
  type: postgresdb

externalPostgresql:
  host: "my.db.host"
  username: "my_db_user"
  database: "my_db"
  existingSecret: "secret-db"

externalRedis:
  host: "redis-cluster"
  username: ""
  port: 6379
  existingSecret: "redis-cluster"

api:
  enabled: true
  path: api
  swagger:
    enabled: true

main:
  count: 1

  pdb:
    enabled: false

  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

  extraEnvVars: &extraEnvVars
    N8N_LOG_LEVEL: "debug"
    N8N_DIAGNOSTICS_ENABLED: "false"
    N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
    N8N_TEMPLATES_ENABLED: "false"
    EXTERNAL_FRONTEND_HOOKS_URLS: ""
    N8N_DIAGNOSTICS_CONFIG_FRONTEND: ""
    N8N_DIAGNOSTICS_CONFIG_BACKEND: ""
    N8N_ONBOARDING_FLOW_DISABLED: "false"
    N8N_PERSONALIZATION_ENABLED: "false"
    HTTP_PROXY: "http://proxy.com:33128"
    HTTPS_PROXY: http://proxy.com:33128
    NO_PROXY: "127.0.0.1,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.local,.svc"
    QUEUE_BULL_PREFIX: "{jobs}"
    QUEUE_BULL_REDIS_CLUSTER_NODES: "...,<nodes>"

  extraSecretNamesForEnvFrom: &httpProxySecret
    - proxy-config

worker:
  mode: queue
  concurrency: 6

  count: 2

  allNodes: false

  autoscaling:
    enabled: true

    minReplicas: 2

    maxReplicas: 1000

    metrics:
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 90

      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 90

  pdb:
    enabled: false

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  extraEnvVars: *extraEnvVars
  extraSecretNamesForEnvFrom: *httpProxySecret

timezone: "Europe/Berlin"
defaultLocale: en

ingress:
  enabled: true
  className: "ingressClass"
  annotations:
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy.org/ssl-redirect-port: "443"

  hosts:
    - host: myn8n.com
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - "myn8n.com"

webhook:
  enabled: true

  mode: queue
  url: "https://webhook.com"

  className: "ingress-ext"

  annotations:
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy.org/ssl-redirect-port: "443"
  hosts:
    - host: webhook.com 
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "webhook.com"

  autoscaling:
    enabled: true

  waitMainNodeReady:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 512Mi
      
  pdb:
    enabled: false

  extraEnvVars: *extraEnvVars
  extraSecretNamesForEnvFrom: *httpProxySecret

diagnostics:
  # -- Whether diagnostics are enabled.
  enabled: false

  # -- Diagnostics config for frontend.
  frontendConfig: ""
  # -- Diagnostics config for backend.
  backendConfig: ""

  postHog:
    # -- API key for PostHog.
    apiKey: ""
    # -- API host for PostHog.
    apiHost: ""

versionNotifications:
  # -- Whether to request notifications about new n8n versions
  enabled: false
  # -- Endpoint to retrieve n8n version information from
  endpoint: ""
  # -- URL for versions panel to page instructing user on how to update n8n instance
  infoUrl: ""


nodeSelector: {}

tolerations: []

affinity: {}
```

As it runs behind corporate proxy, I've setup env vars (both in lower and upper case) to route all traffic via that proxy (squid). 

When I started creating workflow where AI Node agent communicates with open ai api I've noticed that my own setup takes 20+ seconds to complete while cloud one takes 3 second. After debugging I've found out that it makes some suspicious requests to `104.21.48.1` even when it setup to run in isolated mode.  Requests are from worker pods. These requests are hanging up to 20 seconds, then failing, then open ai api requests are executed OK without any hangs.
What could it be?
