### ISSUE TITLE
[n8n] OAuth2 callback URL does not accessible from outside

### ISSUE THREAD

**Issue by burakince** [community-charts/helm-charts#141]
### Describe the bug a clear and concise description of what the bug is.

When we use queue mode and use internal ingress and external webhook address, `https://WEBHOOK_ADDRESS/rest/oauth2-credential/callback` is not accessible from outside.

### What's your helm version?

v3.18.3

### What's your kubectl version?

v1.33.2

### Which chart?

n8n

### What's the chart version?

1.8.7

### What happened?

Currently, it returns HTTP 404 (Not Found) error.

### What you expected to happen?

It must return the respected OAuth2 response data.

### How to reproduce it?

e.g.: POST `https://webhook.myexternaldomain.com/rest/oauth2-credential/callback` must be accessible from outside for the OAuth2 flow.

### Enter the changed values of values.yaml?

```yaml
db:
  type: postgresdb

worker:
  mode: queue

ingress:
  enabled: true
  hosts:
    - host: n8n.myinternaldomain.local
      paths:
        - path: /
          pathType: Prefix

webhook:
  mode: queue
  url: "https://webhook.myexternaldomain.com"

postgresql:
  enabled: true

redis:
  enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

helm install n8n community-charts/n8n --version 1.8.7 --values values.yaml
