### ISSUE TITLE
[n8n] MCP Server Trigger does not work on queue mode

### ISSUE THREAD

**Issue by burakince** [community-charts/helm-charts#148]
### Describe the bug a clear and concise description of what the bug is.

When I enable webhook queue mode, [n8n MCP Server Trigger](https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-langchain.mcptrigger/) is not working.

### What's your helm version?

v3.18.3

### What's your kubectl version?

v1.33.2

### Which chart?

n8n

### What's the chart version?

1.9.1

### What happened?

The MCP endpoint cannot be reached.

### What you expected to happen?

The MCP endpoint must be called successfully.

### How to reproduce it?

Enable webhook queue mode and test MCP Server endpoint.

### Enter the changed values of values.yaml?

```yaml
db:
  type: postgresdb

externalPostgresql:
  host: "postgresql-instance1.ab012cdefghi.eu-central-1.rds.amazonaws.com"
  username: "n8nuser"
  password: "Pa33w0rd!"
  database: "n8n"

worker:
  mode: queue

externalRedis:
  host: "redis-instance1.ab012cdefghi.eu-central-1.rds.amazonaws.com"
  username: "default"
  password: "Pa33w0rd!"

ingress:
  enabled: true
  hosts:
    - host: n8n.mydomain.com
      paths:
        - path: /
          pathType: Prefix

webhook:
  mode: queue

  url: "https://webhook.mydomain.com"
```

### Enter the command that you execute and failing/misfunctioning.

helm install n8n community-charts/n8n --version 1.9.1 --values values.yaml
