### ISSUE TITLE
[n8n] Affinity Configuration Not Split Between Worker and Webhook Pods

### ISSUE THREAD

**Issue by burakince** [community-charts/helm-charts#150]
### Describe the bug a clear and concise description of what the bug is.

Currently, the affinity configuration is being applied uniformly to all n8n pods. However, this approach doesn't account for the differences between worker and webhook pods, which may have distinct scheduling or resource requirements. This can lead to suboptimal pod placement and reduced flexibility in managing workloads.

### What's your helm version?

v3.18.3

### What's your kubectl version?

v1.33.2

### Which chart?

n8n

### What's the chart version?

1.10.0

### What happened?

It applies affinity definition to all pods.

### What you expected to happen?

Affinity rules should be configurable separately for worker and webhook pods to better align with their respective roles and operational needs.

### Enter the changed values of values.yaml?

```yaml
db:
  type: postgresdb

externalPostgresql:
  host: "postgresql-instance1.ab012cdefghi.eu-central-1.rds.amazonaws.com"
  username: "n8nuser"
  password: "Pa33w0rd!"
  database: "n8n"

worker:
  mode: queue

externalRedis:
  host: "redis-instance1.ab012cdefghi.eu-central-1.rds.amazonaws.com"
  username: "default"
  password: "Pa33w0rd!"

ingress:
  enabled: true
  hosts:
    - host: n8n.mydomain.com
      paths:
        - path: /
          pathType: Prefix

webhook:
  mode: queue

  url: "https://webhook.mydomain.com"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: n8n-worker
          app.kubernetes.io/instance: n8n
      topologyKey: kubernetes.io/hostname
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: n8n-webhook
          app.kubernetes.io/instance: n8n
      topologyKey: kubernetes.io/hostname
```

### Enter the command that you execute and failing/misfunctioning.

helm install n8n community-charts/n8n --version 1.10.0 --values values.yaml

### Anything else we need to know?

**Suggestion**:
Update the deployment configuration to allow defining distinct affinity settings for worker and webhook pods, ensuring more granular control over pod scheduling.
