### ISSUE TITLE
[mlflow] model artifacts not saved in remote s3 artifact store

### ISSUE THREAD

**Issue by mohittalele** [community-charts/helm-charts#32]
### Describe the bug a clear and concise description of what the bug is.

I have local minikube cluster. I installed the helm chart with some changed settings. See below for the changed values. Everthing else is same as per default values yaml file. For db backend I am using `bitnami/postgresql` and for s3 storage minio instance. I also have created a initial bucket named "mlflow" in minio. 

And then I created a simple k8s pod to run the simple training example from mlflow docs. This pod has env variables set as : `MLFLOW_TRACKING_URI=http://mlflow.airflow.svc.cluster.local:5000` [Here ](https://raw.githubusercontent.com/mlflow/mlflow/master/examples/sklearn_elasticnet_wine/train.py) is the link to that code. I can see the metadata about the model in UI however , artifact section in UI is empty and also the bucket is empty. 

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

mlflow

### What's the chart version?

latest

### What you expected to happen?

I would expect the artifacts in minio bucket.

### How to reproduce it?

install the helm chart with minio and postgresql config. Run a simple exmple frpom docs. 

### Enter the changed values of values.yaml?

```
backendStore:
    databaseMigration: true
    databaseConnectionCheck: true
    postgres:
      enabled: true
      host: mlflow-postgres-postgresql.airflow.svc.cluster.local
      database: mlflow_db
      user: mlflow
      password: mlflow
artifactRoot:
  proxiedArtifactStorage: true
  s3:
    enabled: true
    bucket: mlflow
    awsAccessKeyId: {{ requiredEnv "MINIO_USERNAME" }}
    awsSecretAccessKey: {{ requiredEnv "MINIO_PASSWORD" }}
extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: minio.airflow.svc.cluster.local
```

### Enter the command that you execute and failing/misfunctioning.

helm install mlflow-release community-charts/mlflow --values values.yaml
