### ISSUE TITLE
[mlflow] `Update to MLflow>=2.2.1` - Patch Critical Remote file access vulnerability

### ISSUE THREAD

**Issue by safoinme** [community-charts/helm-charts#43]
### Is your feature request related to a problem ?

There is a reported critical remote file access vulnerability within the older version of MLflow, with the `mlflow server` and `mlflow ui` .  More details here: https://github.com/advisories/GHSA-xg73-94fp-g449

### Describe the solution you'd like.

Can we please get an update to `MLflow >= 2.21`!

### Describe alternatives you've considered.

-

**Comment by ampx-mg** [comment]
We would appreciate this update as well, is there any way we can help @burakince ?

**Comment by bobrasey-verusen** [comment]
Opened [PR47](https://github.com/community-charts/helm-charts/pull/47) to upgrade MLFlow to 2.4.2.

**Comment by spencerjbeckwith** [comment]
If it's helpful, I was able to use this chart with an updated mlflow by just changing the image to a more up-to-date version, such as [bitnami/mlflow](https://hub.docker.com/r/bitnami/mlflow).

```
image:
  repository: bitnami/mlflow
```

Though this chart would definitely benefit from an update.

**Comment by bobrasey-verusen** [comment]
We found the community too poorly supported and moved to Databricks.

**Comment by burakince** [comment]
Dear All,  

The MLflow chart includes a default image repository and tag; however, you can override these settings to use a custom image and tag. The latest tag has been updated to the latest MLflow version (2.19.0). If needed, you can modify the configuration settings as shown below:  

```yaml
# MLflow image configuration
image:
  # -- Docker image repository
  repository: YOUR_SERVER/YOUR_ORGANIZATION/YOUR_IMAGE_NAME
  # -- Docker image pull policy
  pullPolicy: IfNotPresent
  # -- Docker image tag (defaults to the app version)
  tag: "YOUR_TAG"
```  

As this addresses the issue, I am closing it. Should you require further assistance, please feel free to reopen the issue.  

Best regards,  
Burak
