### ISSUE TITLE
[mlflow] Add option to create a Kubernetes secret as part of the chart

### ISSUE THREAD

**Issue by v9rt3x** [community-charts/helm-charts#53]
### Is your feature request related to a problem ?

In case one would create an ingress resource with annotations referring to a secret it would be nice to be able to deploy that dependency along with chart.

### Describe the solution you'd like.

Additional helm value to add secret with a list of key-value pairs which represents the data of the secret

### Describe alternatives you've considered.

-

**Comment by burakince** [comment]
Hi @v9rt3x ,

Apologies for the delayed response, and thank you for reaching out!

I’d love to help, but I’d appreciate some clarification on your request. Typically, when dealing with TLS certificates for ingress, we manage secrets alongside ingress resources, often using [cert-manager](https://cert-manager.io/) to handle this seamlessly.

Are you suggesting that the Helm chart should create the secret for the ingress certificate, or are you referring to a different use case? I’d like to make sure I fully understand the requirement so we can explore the best approach.

Looking forward to your response!

Best regards,
Burak Ince

**Comment by xhensiladoda** [comment]
Hello, I would be interested to this feature as well.
We were using the Bitnami chart and due to their recent announcement, we would like to use this helm chart to deploy MLFlow, and I am encountering the same issue as exposed here.
Just for clarification, if I understand correctly the request of @v9rt3x , he means to be able to deploy extra resources, secrets in this specific case, that might be needed from the chart. In this way, we do not have to create the resources with custom additional charts ourselves.
Just to make an example, Bitnami supports this feature through the [extraDeploy](https://artifacthub.io/packages/helm/bitnami/mlflow?modal=values&path=extraDeploy) value.
> | `extraDeploy`            | Array of extra objects to deploy with the release  
And this is the template: https://github.com/bitnami/charts/blob/da7242c2a0b35e2430e2c079df65dd23f5b57517/bitnami/mlflow/templates/extra-list.yaml#L6
In my case, I was using the Bitnami chart and I used is as this:
```yaml
extraDeploy:
  # SecretStore using IRSA permissions
  - apiVersion: external-secrets.io/v1
    kind: SecretStore
    metadata:
      name: mlflow
      labels:
        payfit.net/team: data-engineering
    spec:
      provider:
        aws:
          auth:
            jwt:
              serviceAccountRef:
                name: mlflow-tracking
          region: {{ .Values.aws.region }}
          service: SecretsManager

  # ExternalSecret to retrieve RDS credentials
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: mlflow-rds-credentials
      labels:
        payfit.net/team: data-engineering
    spec:
      secretStoreRef:
        name: mlflow
        kind: SecretStore
      target:
        name: mlflow-rds-credentials
      data:
        - secretKey: username
          remoteRef:
            key: mlflow-abcd-mlflow-credentials
            property: master_username
        - secretKey: password
          remoteRef:
            key: mlflow-abcd-mlflow-credentials
            property: master_password
```
Would it be possible to add to this chart also the support of extra Kubernetes resources? It would be a life changer and a clean solution in order to have everything plugged together without the need of additional charts.
I would be interested to contribute if this request is not priority for you.
Thanks for your attention, and thanks for making this chart available for the community 🙏
