### ISSUE TITLE
[outline] I cant reverse proxy with external nginx normally

### ISSUE THREAD

**Issue by Qarasique** [community-charts/helm-charts#65]
### Is your feature request related to a problem ?

I cant reverse proxy to loadbalancer type of service. Because listen URL of ouline is parsed only from nginx hosts
Its lead to unlimited problems with redirects. etc....

### Describe the solution you'd like.

Maybe add variable to define "URL=" ENV, not templating it

### Describe alternatives you've considered.

Maybe add variable to define "URL=" ENV, not templating it

**Comment by burakince** [comment]
Hi @Qarasique 

Could you please share your values.yaml file?

For example. This is what I use for my setup and it works fine.

```yaml
replicaCount: 1

secretKey: REDACTED
utilsSecret: REDACTED

strategy:
  type: Recreate

logging:
  level: warn

fileStorage:
  mode: local

  local:
    persistence:
      enabled: true
      existingClaim: outline-volume

auth:
  gitea:
    enabled: true
    clientId: REDACTED
    clientSecret: REDACTED
    baseUrl: "https://git.192.168.0.201.nip.io"

externalRedis:
  host: outlineredis-master.outlineredis.svc.cluster.local
  password: REDACTED

externalPostgresql:
  host: postgres-service.default.svc.cluster.local
  username: REDACTED
  password: REDACTED
  database: outline

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  hosts:
    - host: "docs.192.168.0.201.nip.io"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: "docs-selfsigned-cert-tls"
      hosts:
        - "docs.192.168.0.201.nip.io"

web:
  forceHttps: false
  skipSSLVerification: true

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 1Gi
```

Maybe it can help to compare with your settings. And if you can share your settings, I can try to reproduce the issue.

Best,
Burak
