### ISSUE TITLE
n8n: Deployment Workers stuck in crash loop

### ISSUE THREAD

**Issue by rv-nkoehne** [community-charts/helm-charts#80]
### Describe the bug a clear and concise description of what the bug is.

deployment-worker.yaml doesn't execute shell upon start up. Need to add "bin/sh" before running "n8n"
File should be updated to look like so on line 62:

```
command: ["/bin/sh", "n8n"]

```

### What's your helm version?

3

### What's your kubectl version?

v1.32.2

### Which chart?

n8n

### What's the chart version?

latest

### Enter the command that you execute and failing/misfunctioning.

See comments

**Comment by burakince** [comment]
Hi @rv-nkoehne ,

I already use latest version with two workers in my cluster and it doesn't get any error. Could you please share which error message do you receive?

<img width="924" alt="Image" src="https://github.com/user-attachments/assets/fa27d54f-81c4-45a7-a1e4-cd2be853e902" />

<img width="847" alt="Image" src="https://github.com/user-attachments/assets/64fcbf07-95be-431f-8bff-226d8cadba76" />

**Comment by burakince** [comment]
Also I need your values.yaml file details to reproduce the error.

**Comment by burakince** [comment]
You can also check this link, where workers were tested with Kind cluster v1.32.0, and everything worked fine:  
[GitHub Actions Run](https://github.com/community-charts/helm-charts/actions/runs/14046425468/job/39328115728#step:12:913)

It seems like a configuration issue. If you can share your configurations, I'd be happy to take a look and help troubleshoot.

Best regards,

**Comment by rv-nkoehne** [comment]
Appreciate you getting back so fast! Here is my values.yaml:

`# Define hostname anchor at the top of the file

image:
  repository: n8nio/n8n
  tag: "stable"

log:
  level: warn

db:
  type: postgresdb

externalPostgresql:
  host: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/rds-host"
  username: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/rds-username"
  password: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/rds-password"
  database: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/rds-database-name"

main:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 512Mi
  extraEnvVars:
    QUEUE_HEALTH_CHECK_ACTIVE: "true"

worker:
  extraEnvVars:
    QUEUE_HEALTH_CHECK_PORT: "5678"
  mode: queue
  autoscaling:
    enabled: true

externalRedis:
  host: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/redis-host"
  username: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/redis-username"
  password: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/redis-password"

ingress:
  enabled: true
  className: "alb"
  annotations: {
    "alb.ingress.kubernetes.io/scheme": "internet-facing",
    "alb.ingress.kubernetes.io/load-balancer-name": "aip-n8n-alb",
    "alb.ingress.kubernetes.io/certificate-arn": "ref+awsssm://shield-vault/eks/aip-k8s/n8n/alb-certificate-arn",
    "alb.ingress.kubernetes.io/subnets": "ref+awsssm://shield-vault/eks/aip-k8s/n8n/alb-subnets",
    "alb.ingress.kubernetes.io/backend-protocol": "HTTP",
    "alb.ingress.kubernetes.io/target-type": "ip",
    "alb.ingress.kubernetes.io/listen-ports": '[{"HTTPS": 443}]',
    "alb.ingress.kubernetes.io/healthcheck-path": "/healthz"
  }


service:
  type: NodePort
  port: 5678
  name: http
  annotations: {}

livenessProbe:
  httpGet:
    path: /healthz
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz/readiness
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3`

**Comment by rv-nkoehne** [comment]
Deploying to Amazon EKS and while the deployment container (n8n) comes up fine, none of the deployment-workers come up (n8n-worker). After executing into the worker pods with a kubectl command: ` kubectl exec -it n8n-worker-7659c76bcb-tzfq9 -n n8n -- /bin/sh` they finally start passing health checks and come up fine.

**Comment by burakince** [comment]
Hi @rv-nkoehne,

Thank you for reaching out! Here are some recommendations and clarifications regarding your configuration:

- **Encryption Key**: If you don’t set a value for `encryptionKey`, it will be auto-generated. However, if this key is lost over time, you won’t be able to restore your workflows and data. To avoid this risk, I strongly recommend storing it in AWS Secrets Manager and passing it via Parameter Store. You can refer to the AWS documentation for more details: [[AWS Systems Manager Parameter Store & Secrets Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html)](https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html). You can find the current `encryptionKey` from the exist secret.

- **Image Tag**: We always release the latest stable version with the chart, but I recommend specifying a specific version instead of using the `stable` tag. Using `stable` may lead to caching issues similar to those encountered with the `latest` tag. Of course, this is ultimately your decision.

- **Health Check Variables**: You don’t need to explicitly set `QUEUE_HEALTH_CHECK_ACTIVE` and `QUEUE_HEALTH_CHECK_PORT` as they are already defined in the configuration.

- **Autoscaling**: If you plan to use autoscaling, I strongly suggest defining resource requests and limits. Without these, the Horizontal Pod Autoscaler (HPA) will encounter errors in the background, preventing autoscaling from functioning correctly.

- **Liveness & Readiness Probes**: There’s no need to manually set `livenessProbe.httpGet.path` and `readinessProbe.httpGet.path` since they already have default values.

Below is a refined version of your `values.yaml` file. Could you please try using this and let me know if you encounter any errors? If so, sharing the exact error message would help us troubleshoot further.

```yaml
image:
  tag: "stable"

encryptionKey: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/encryptionKey"

log:
  level: warn

db:
  type: postgresdb

externalPostgresql:
  host: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/rds-host"
  username: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/rds-username"
  password: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/rds-password"
  database: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/rds-database-name"

main:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 512Mi

worker:
  mode: queue
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 1Gi

externalRedis:
  host: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/redis-host"
  username: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/redis-username"
  password: "ref+awsssm://shield-vault/eks/aip-k8s/n8n/redis-password"

ingress:
  enabled: true
  className: "alb"
  annotations: {
    "alb.ingress.kubernetes.io/scheme": "internet-facing",
    "alb.ingress.kubernetes.io/load-balancer-name": "aip-n8n-alb",
    "alb.ingress.kubernetes.io/certificate-arn": "ref+awsssm://shield-vault/eks/aip-k8s/n8n/alb-certificate-arn",
    "alb.ingress.kubernetes.io/subnets": "ref+awsssm://shield-vault/eks/aip-k8s/n8n/alb-subnets",
    "alb.ingress.kubernetes.io/backend-protocol": "HTTP",
    "alb.ingress.kubernetes.io/target-type": "ip",
    "alb.ingress.kubernetes.io/listen-ports": '[{"HTTPS": 443}]',
    "alb.ingress.kubernetes.io/healthcheck-path": "/healthz"
  }

service:
  type: NodePort
  port: 5678
  name: http
  annotations: {}

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
```

Looking forward to your feedback! 😊

Best, 
Burak
